contact/urls.py
from django.urls import path

from contact.views import ContactView

app_name = "contact"
urlpatterns = [
    path("", ContactView.as_view(), name="landing"),
]

core/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.generic import TemplateView

from story.sitemap import BlogSiteMap

from . import views
from .sitemap import StaticViewSitemap

sitemaps = {"website": StaticViewSitemap, "blog": BlogSiteMap}

app_name = "core"
urlpatterns = [
    # path(r'^test-404/$', 'core.views.error404'),
    path("events/", views.events, name="events"),
    path("events/map/", views.events_map, name="events_map"),
    path("events/calendar.ics", views.events_ical, name="icalendar"),
    path("resources/", views.resources, name="resources"),
    path("newsletter/", views.newsletter, name="newsletter"),
    path("faq/", views.faq, name="faq"),
    path("foundation/", views.foundation, name="foundation"),
    path("foundation/governing-document/", views.governing_document, name="foundation-governing-document"),
    path("contribute/", views.contribute, name="contribute"),
    path("2015/", views.year_2015, name="year_2015"),
    path("2016-2017/", views.year_2016_2017, name="year_2016_2017"),
    path("terms-conditions/", views.terms_conditions, name="terms-conditions"),
    path("privacy-cookies/", views.privacy_cookies, name="privacy-cookies"),
    # path(r'^workshop-box/$', views.workshop_box, name='workshop-box'),
    path("coc/", views.coc, name="coc"),
    # path(r'^crowdfunding-donors/$', views.crowdfunding_donors, name='crowdfunding-donors'),
    path("server-error/", views.server_error, name="server_error"),
    path("<slug:page_url>/", views.event, name="event"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="core/txt/robots.txt", content_type="text/plain"),
        name="robots",
    ),
    path("", views.index, name="index"),
    path(
        "google3ef9938c7b93b707.html",
        TemplateView.as_view(template_name="google3ef9938c7b93b707.html"),
        name="google_site_verification",
    ),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
]

djangogirls/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog

from core.views import coc_legacy

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    re_path(r"^coc/(?:(?P<lang>[a-z-]+)/)?$", coc_legacy, name="coc_legacy"),
    # Redirection for old CoC's flatpages:
    path("pages/coc/", RedirectView.as_view(url="/coc/", permanent=True)),
    path("pages/coc-es-la/", RedirectView.as_view(url="/coc/es/", permanent=True)),
    path("pages/coc-fr/", RedirectView.as_view(url="/coc/fr/", permanent=True)),
    path("pages/coc-kr/", RedirectView.as_view(url="/coc/ko/", permanent=True)),
    path("pages/coc-pt-br/", RedirectView.as_view(url="/coc/pt-br/", permanent=True)),
    path("pages/coc/rec/", RedirectView.as_view(url="/coc/pt-br/", permanent=True)),
]

urlpatterns += i18n_patterns(
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    # Redirect old links:
    path("pages/in-your-city/", RedirectView.as_view(url="/organize/", permanent=True)),
    path("admin", RedirectView.as_view(url="/admin/", permanent=True)),
    path("admin/core/eventpage/<int>/", RedirectView.as_view(pattern_name="admin:core_event_change")),
    # Admin link for password reset
    # See:
    # https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/
    # login.html#L61
    path(
        "admin/password_reset/",
        RedirectView.as_view(url="/account/password_reset", permanent=True),
        name="admin_password_reset",
    ),
    path("tinymce/", include("tinymce.urls")),
    # Regular links:
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("coach/", include("coach.urls")),
    path("contact/", include("contact.urls")),
    path("donate/", include("donations.urls")),
    path("organize/", include("organize.urls")),
    path("story/", include("story.urls")),
    path("jobs/", include("jobboard.urls")),
    # path('', include('sponsor.urls')),
    path("", include("applications.urls")),
    path("", include("core.urls")),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

donations/urls.py
from django.urls import path

from . import views

app_name = "donations"

urlpatterns = [
    path("", views.index, name="index"),
    path("donate/", views.donate, name="donate"),
    path("charge/", views.charge, name="charge"),
    path("success/<str:currency>/<str:amount>/", views.success, name="success"),
    path("error/", views.error, name="error"),
    path("sponsors/", views.sponsors, name="sponsors"),
    path("crowdfunding/", views.crowdfunding, name="crowdfunding"),
]

organize/urls.py
from django.urls import path

from . import views

app_name = "organize"
urlpatterns = [
    path("", views.index, name="index"),
    path("prerequisites/", views.prerequisites, name="prerequisites"),
    path("commitment/", views.commitment, name="commitment"),
    path("form/thank_you/", views.form_thank_you, name="form_thank_you"),
    path("form/<slug:step>/", views.organize_form_wizard, name="form_step"),
    # path('remote_or_in_person/', views.remote_or_in_person, name='remote_or_in_person'),
    path("suspend/", views.suspend, name="suspend"),
    path("event_funding/", views.event_funding, name="event_funding"),
    path("slack/", views.slack, name="slack"),
]

story/urls.py
from django.urls import path

from story.views import StoryListView

app_name = "story"
urlpatterns = [
    path("", StoryListView.as_view(), name="stories"),
]

core/models/organizer.py
from django.db import models

from .event import Event
from .user import User


class OrganizerIssue(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    organizer = models.ForeignKey(User, related_name="oganizer", on_delete=models.deletion.CASCADE)
    event = models.ForeignKey(to=Event, null=True, blank=True, related_name="event", on_delete=models.deletion.SET_NULL)
    date_reported = models.DateField()
    reported_by = models.CharField(max_length=100)
    reporter_email = models.EmailField(max_length=100)
    issue = models.TextField()
    issue_handled = models.BooleanField()
    issue_handled_by = models.ForeignKey(
        to=User, null=True, blank=True, related_name="staff_responsible", on_delete=models.deletion.SET_NULL
    )
    findings = models.TextChoices(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.organizer.get_full_name()} - {self.event}"

    def blacklist_organizer(self):
        user = User.objects.get(id=self.organizer)
        user.is_blacklisted = True
        user.save()

core/admin/forms/event_page_content.py
import tinymce
from django import forms
from tinymce.widgets import AdminTinyMCE


class EventPageContentForm(forms.ModelForm):
    class Meta:
        widgets = {
            "content": AdminTinyMCE(
                mce_attrs={
                    "plugins": tinymce.settings.DEFAULT_CONFIG["plugins"] + " | code",
                    "toolbar": tinymce.settings.DEFAULT_CONFIG["toolbar"] + " | code",
                },
            )
        }
        fields = (
            "event",
            "name",
            "content",
            "background",
            "position",
            "is_public",
        )

core/admin/forms/organizer.py
from django import forms
from models.event import Event
from models.organizer import OrganizerIssue
from models.user import User


class OrganizerIssueForm(forms.ModelForm):
    organizer = forms.ModelChoiceField(queryset=User.objects.all())
    event = forms.ModelChoiceField(queryset=Event.objects.all())
    issue_handled_by = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True))

    class Meta:
        model = OrganizerIssue
        fields = (
            "organizer",
            "event",
            "date_reported",
            "reported_by",
            "issue",
            "issue_handled",
            "issue_handled_by",
            "findings",
            "comments",
            "last_updated",
        )

core/admin/forms/organizerissue.py
from django import forms

from core.models.event import Event
from core.models.organizerissue import OrganizerIssue
from core.models.user import User


class OrganizerIssueForm(forms.ModelForm):
    organizer = forms.ModelChoiceField(queryset=User.objects.all())
    event = forms.ModelChoiceField(queryset=Event.objects.all())
    issue_handled_by = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True))

    class Meta:
        model = OrganizerIssue
        fields = (
            "organizer",
            "event",
            "date_reported",
            "reported_by",
            "issue",
            "issue_handled",
            "issue_handled_by",
            "findings",
            "comments",
        )

core/admin/forms/user.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import User


class UserCreationForm(forms.ModelForm):
    error_messages = {
        "password_mismatch": _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."),
    )

    class Meta:
        model = User
        fields = ("email",)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserLimitedChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")

core/views.py
import icalendar
from django.conf import settings
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import TemplateDoesNotExist
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_date_extensions.fields import ApproximateDate

from applications.questions import get_organiser_menu
from patreonmanager.models import FundraisingStatus
from story.models import Story

from .models import Event, User


def index(request):
    blogs = Story.objects.filter(is_story=False).order_by("-created")[:3]
    city_count = Event.objects.values("city").distinct().count()
    country_count = Event.objects.values("country").distinct().count()
    future_events = Event.objects.future()
    organizers = User.objects.all().count()
    stories = Story.objects.filter(is_story=True).order_by("-created")[:2]

    return render(
        request,
        "core/index.html",
        {
            "future_events": future_events,
            "stories": stories,
            "blogposts": blogs,
            "patreon_stats": FundraisingStatus.objects.all().first(),  # TODO: This isn't used
            "organizers_count": organizers,
            "cities_count": city_count,
            "country_count": country_count,
        },
    )


def events(request):
    return render(
        request,
        "core/events.html",
        {
            "future_events": Event.objects.future(),
            "past_events": Event.objects.past(),
        },
    )


def events_map(request):
    return render(
        request,
        "core/events_map.html",
        {"events": Event.objects.public().order_by("date"), "mapbox_access_token": settings.MAPBOX_ACCESS_TOKEN},
    )


def resources(request):
    return render(request, "core/resources.html", {})


def event(request, page_url):
    now = timezone.now()
    now_approx = ApproximateDate(year=now.year, month=now.month, day=now.day)

    try:
        event_obj = get_object_or_404(Event, page_url=page_url.lower())
    except Event.MultipleObjectsReturned:
        event_obj = Event.objects.filter(page_url=page_url.lower()).order_by("-date").first()

    user = request.user
    user_is_organizer = user.is_authenticated and event_obj.has_organizer(user)
    is_preview = "preview" in request.GET
    can_preview = user.is_superuser or user_is_organizer or is_preview
    is_past = event_obj.date <= now_approx if event_obj.date else False

    if not (event_obj.is_page_live or can_preview) or event_obj.is_frozen:
        return render(
            request, "applications/event_not_live.html", {"city": event_obj.city, "page_url": page_url, "past": is_past}
        )

    return render(
        request,
        "core/event.html",
        {
            "event": event_obj,
            "menu": event_obj.menu.all(),
            "organizer_menu": get_organiser_menu(page_url),
            "content": event_obj.content.prefetch_related("coaches", "sponsors").filter(is_public=True),
            "page_url": page_url,
            "user": user,
        },
    )


def events_ical(request):
    events = Event.objects.public().order_by("-date")
    calendar = icalendar.Calendar()
    calendar["summary"] = _("List of Django Girls events around the world")
    for event in events:
        ical_event = event.as_ical()
        if ical_event is None:
            continue  # Skip events with an approximate date
        calendar.add_component(ical_event)

    return HttpResponse(calendar.to_ical(), content_type="text/calendar; charset=UTF-8")


def newsletter(request):
    return render(request, "core/newsletter.html", {})


def faq(request):
    return render(request, "core/faq.html", {})


def foundation(request):
    return render(request, "core/foundation.html", {})


def governing_document(request):
    return render(request, "core/governing_document.html", {})


def contribute(request):
    return render(request, "core/contribute.html", {})


def year_2015(request):
    return render(
        request,
        "core/2015.html",
        {
            "events": Event.objects.public().filter(date__lt="2016-01-01").order_by("date"),
            "mapbox_access_token": settings.MAPBOX_ACCESS_TOKEN,
        },
    )


def year_2016_2017(request):
    return render(
        request,
        "core/2016-2017.html",
        {
            "events": Event.objects.public().filter(date__lt="2017-08-01", date__gte="2016-01-01").order_by("date"),
            "mapbox_access_token": settings.MAPBOX_ACCESS_TOKEN,
        },
    )


def terms_conditions(request):
    return render(request, "core/terms_conditions.html", {})


def privacy_cookies(request):
    return render(request, "core/privacy_cookies.html", {})


# This view's URL is commented out, so avoid coverage hit by commenting out the view also
# def workshop_box(request):
#     return render(request, 'core/workshop_box.html', {})


def server_error(request):
    return HttpResponse(status=500)


def coc(request):
    template_name = "core/coc.html"
    return render(request, template_name)


def coc_legacy(request, lang=None):
    if lang is None:
        lang = "en"
    template_name = f"core/coc/{lang}.html"
    try:
        return render(request, template_name)
    except TemplateDoesNotExist as err:
        raise Http404(_("No translation for language %(lang)s") % {"lang": lang}) from err


# This view's URL is commented out, so avoid coverage hit by commenting out the view also
# def crowdfunding_donors(request):
#     donor_list = Donor.objects.filter(visible=True).order_by('-amount')
#     return render(request, 'core/crowdfunding_donors.html', {
#         'donor_list': donor_list,
#         'quotes': DONOR_QUOTES,
#     })

templates/core/events_map.html
{% extends 'global/base.html' %}
{% load i18n static %}

{% block extra_css %}
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
{% endblock %}

{% block extra_js %}
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
{% endblock %}

{% block content %}

    <div class="container">
        <h2>{% trans "Django Girls events" %}</h2>
        <div id="map"></div>
    </div>

    {% include "core/map.html" with events=events mapbox_access_token=mapbox_access_token %}

{% endblock %}

templates/core/index.html
{% extends 'global/base.html' %}
{% load i18n rev static %}

{% block extra_js %}
    <script type="text/javascript" src="{% static_rev 'js/global.js' %}"></script>
{% endblock %}

{% block content %}

    <section id="box-with-picture">
      <div class="black-canvas">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1>{% trans "We inspire women to fall in love with programming." %}</h1>
                    <p>
                        {% trans "Django Girls organize free Python and Django workshops, create open sourced online tutorials and curate amazing first experiences with technology." %}
                    </p>
                </div>
            </div>
        </div>
      </div>
    </section>

    <div class="container">
        <section id="about">
            <div class="row">
                <div class="col-md-6">
                    <h2>{% trans "What is Django Girls?" %}</h2>
                    <p>
                      {% url 'core:foundation' as foundation_url %}
                      {% blocktrans trimmed %}
                        Django Girls is a <a href="{{ foundation_url }}">non-profit organization</a> and a community that empowers and helps women
                        to organize free, one-day programming workshops by providing tools, resources and support. We are a volunteer run organization
                        with hundreds of people contributing to bring more amazing women into the world of technology.
                        We are making technology more approachable by creating resources designed with empathy.
                      {% endblocktrans %}
                    </p>
                    <p>
                      {% blocktrans trimmed %}
                        During each of our events, 30-60 women build their first web application using HTML, CSS, Python and Django.
                      {% endblocktrans %}
                    </p>
                    {# <p><a href="">Learn more about Django Girls »</a></p> #}
                </div>
                <div class="col-md-6">
                  <iframe src="//player.vimeo.com/video/953132851?title=0&amp;byline=0&amp;portrait=0&amp;color=ff9933" width="585" height="329" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <h2>{% trans "Django Girls impact" %}</h2>
                    <p>
                    {% url 'core:events_map' as event_map_url %}
                      {% blocktrans trimmed %}
                        Since 2014, an army of <span class="highlighted-number">{{ organizers_count }} volunteers</span> in the
                        Django Girls community organized <span class="highlighted-number">{{ all_events_count }} events.</span>
                        We've been to <span class="highlighted-number">{{ cities_count }} cities</span> in
                        <span class="highlighted-number">{{ country_count }} countries</span> (<a href="{{ event_map_url }}">see them all on a map</a>).
                      {% endblocktrans %}
                    </p>
                    <p>
                      {% blocktrans trimmed %}
                        A total of <span class="highlighted-number">{{ attendees_sum }} incredible women attended</span>
                        events organized by members of our community.
                      {% endblocktrans %}
                    </p>
                    <p><a href="{% url 'core:year_2016_2017' %}">{% trans "Read our Annual Report to learn about the impact we make" %} »</a></p>
                </div>

               <div class="col-md-6">
                    <h2>{% trans "Bring Django Girls to your city!" %}</h2>
                    <p>{% trans "Is there no Django Girls event in your city? You can help make it happen!" %}</p>
                    <p>
                      {% blocktrans trimmed %}
                        We open sourced the <a href="http://organize.djangogirls.org/">Organizer Manual</a> that provides
                        you with all information required to organize Django Girls workshop. By volunteering to organize,
                        you're joining a vibrant and supportive community of {{ organizers_count }} organizers all over the world!
                      {% endblocktrans %}
                    </p>
                    <p><a class="btn" href="{% url 'organize:index' %}">{% trans "Apply to organize a workshop" %}</a></p>
                </div>
            </div>
        </section>

        <section id="events">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        {% trans "Upcoming events" %}
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:icalendar' %}">ICAL</a>
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:events_map' %}">{% trans "MAP" %}</a>
                    </h2>
                </div>
            </div>

            <div class="upcoming-events">
                <div class="row-container">
                    {% for event in future_events %}
                      {% if forloop.first %}<div class="row">{% endif %}
                      <div class="col event">
                        {% include 'includes/_event.html' with event=event %}</div>
                        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                          {% if forloop.last %}</div>{% endif %}
                    {% endfor %}    
                </div>
                <div class="show-more"><a href="javascript:;">
                    {% blocktrans %}Show all {{ future_events_count }} upcoming events{% endblocktrans %} »
                </a></div>
            </div>
        </section>

        <section id="story">
            <div class="row">
                <div class="col-md-6">
                    <h2>{% trans "Badass Django Ladies" %}</h2>
                    <p>{% trans "Each week we try to introduce one badass lady who uses Python or Django and highlight her work:" %}</p>

                    {% for story in stories %}
                    {% if forloop.first %}<div class="row">{% endif %}
                      <div class="col story">
                        {% include 'includes/_story.html' with story=story %}</div>
                      {% if forloop.counter|divisibleby:2 %}</div><div class="row">{% endif %}
                      {% if forloop.last %}</div>{% endif %}
                    {% endfor %}
                    <p><a href="{% url 'story:stories' %}">{% trans "Read all Django Stories" %} »</a></p>
                </div>
                <div class="col-md-6">
                    <h2>{% trans "Latest from our blog" %}</h2>
                    {% for blog in blogposts %}
                        <a href="{{ blog.post_url }}" target="_blank" class="post-title">{{ blog.name }}</a>
                        <p class="post-content">{{ blog.content|striptags|truncatewords:25 }} <a href="{{ blog.post_url }}" target="_blank">{% trans "Read all" %} »</a></p>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section id="support">
            <div class="row">
                <div class="col-md-6">
                    <h2>{% trans "Support our work" %}</h2>
                    <p>{% trans "Django Girls is a volunteer run organization, and we depend on your support to make it happen." %}</p>
                    <p class="support-stats">
                      {% blocktrans trimmed %}
                        <span class="highlighted-number">$1,060</span> of <span class="highlighted-number">$2,500</span> monthly goal pledged
                      {% endblocktrans %}
                    </p>
                    <div class="support-bar">
                      <div class="pledge" style="width: 42%">42%</div>
                    </div>
                    <a class="btn" href="http://patreon.com/djangogirls">{% trans "Make a recurring donation on Patreon" %}</a>
                    <p class="partnership">
                    {% url 'contact:landing' as contact_url %}
                    {% url 'donations:index' as donations_url %}
                      {% blocktrans trimmed %}
                        You can also send us a one <a href="{{ donations_url }}">time donation</a>.
                        If you would like to discuss a bigger partnership, <a href="{{ contact_url }}">please get in touch</a>.
                      {% endblocktrans %}
                    </p>
                </div>

                 <div class="col-md-6">
                    <h2>{% trans "Stay up to date!" %}</h2>
                    <p>
                      {% blocktrans trimmed %}
                        Subscribe to Django Girls Dispatch to receive the latest and greatest from our community every two weeks, straight to your inbox!
                      {% endblocktrans %}
                    </p>
                     <div id="mc_embed_signup">
                         <form action="//djangogirls.us8.list-manage.com/subscribe/post?u=5a007b2dabdeddc350bdbbaed&amp;id=d278270e6f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                             <div id="mc_embed_signup_scroll">
                                 <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="{% trans "email address" %}" required>
                                 <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                 <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5a007b2dabdeddc350bdbbaed_d278270e6f" tabindex="-1" value=""></div>
                                 <input type="submit" value="{% trans "Subscribe" %}" name="subscribe" id="mc-embedded-subscribe" class="button">
                             </div>
                         </form>
                     </div>

                    <p>
                        <a href="{% url 'core:newsletter' %}">{% trans "See the Django Girls Dispatch archives" %} »</a>
                    </p>

                    <h2>{% trans  "Check out our podcast!" %}</h2>
                    <p>
                      {% blocktrans trimmed %}
                        We have a new <a href="https://anchor.fm/djangogirls">podcast</a> that is being hosted by trustees 
                        <a href="http://blog.djangogirls.org/post/138923168468"> Aisha</a> and <a href="http://blog.djangogirls.org/post/172001842084">Leona</a> 
                        where they talk with many awesome people from our community. Check out the <a href="https://anchor.fm/s/7aa83714/podcast/rss">RSS Feed</a> 
                        for the <a href="https://anchor.fm/djangogirls">podcast</a> which is available on multiple platforms such as 
                        <a href="https://podcasts.apple.com/us/podcast/django-girls-podcast/id1602881437">Apple Pod</a>, 
                        <a href="https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy83YWE4MzcxNC9wb2RjYXN0L3Jzcw?ep=14">Google Pod</a>, 
                        <a href="https://music.amazon.ca/podcasts/afe571fc-bc45-4fcb-871f-3b5a4bb4560f/django-girls-podcast?ref=dm_sh_pXP60O3XBTy3Vb5o5JmSB1coQ">Amazon Music</a>, 
                        and <a href="https://open.spotify.com/show/5sHA8wy4ttUtPgwXHL2lf5">Spotify</a> . 
                      {% endblocktrans %}
                    </p>
                </div>
            </div>
            </section>

        <section id="sponsors">
            <div class="row">
                <div class="col-md-12">
                    <h2>{% trans "They already sponsor us! 💕" %}</h2>
                    <p>
                      {% blocktrans trimmed %}
                        These incredible companies made a pledge to diversity and are actively helping us to change the ratio in the tech industry. <br />
                        If you wish to join them, support us on <a href="https://www.patreon.com/djangogirls">Patreon</a>
                        or <a href="{{ contact_url }}">drop us a line</a>.
                      {% endblocktrans %}
                    </p>
                </div>
            </div>

            {% include 'includes/_main_sponsors.html' %}
        </section>

        <section id="supporters">
            <div class="row">
                <div class="col-md-12">
                    <h3 style="margin-top: 50px">{% trans "They already support us! 💕" %}</h3>
                    <p>
                        {% blocktrans trimmed %}
                            These incredible companies are actively helping us to change the ratio in the tech industry by supporting us in other ways. <br />
                            If you wish to join them, <a href="{{ contact_url }}">drop us a line</a>.
                        {% endblocktrans %}
                    </p>
                </div>
            </div>

            {% include 'includes/_main_supporters.html' %}
        </section>
    </div>
{% endblock %}

templates/core/translator_invite_success.html
{% extends 'global/base.html' %}
{% block title %}Join the Django Girls Translating Team{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>🎉 YAY 🎉</h2>

                {% include 'includes/_info_messages.html' %}

                <p>The invitation is on the way, congrats!</p>
            </div>
        </div>
    </div>
{% endblock %}